### ISSUE TITLE
about Sponsoring

### ISSUE THREAD

**Issue by tsingson** [kkrypt0nn/spaceflake#4]
would u please setup a Sponsoring as one-time Sponsoring?

i love this repo, thanks a lot for great works.

**Comment by kkrypt0nn** [comment]
Hey there!

Thanks a lot for the positive feedback, for the one time sponsoring I've been having issues with GitHub and their sponsorship system so I simply use [Ko-fi](https://ko-fi.com/kkrypt0nn)
