### ISSUE TITLE
any plan of spaceflake in rust?

### ISSUE THREAD

**Issue by tsingson** [kkrypt0nn/spaceflake#7]
rt.

thanks for great work.

**Comment by kkrypt0nn** [comment]
Thanks for your positive feedback. :)

No plans on doing a port to Rust for the following reasons:

- I never learned that language and learning a language just to make a port is not the way I enjoy learning a language
- As I do not know Rust, I have no projects in Rust where I personally could make use of the library

The first purpose of Spaceflakes was in my personal projects. *(Most of them are in Go.)* I then decided to make publicly available in case someone could make good use of it, in Go project.
